name: Build APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        # Update and install necessary tools
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk wget unzip libffi-dev python3-venv

        # Set up Android SDK
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
        unzip tools.zip
        mv cmdline-tools tools
        cd ~

        # Set environment variables
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/tools/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV

        # Install required SDK components
        yes | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager \
          "platform-tools" \
          "build-tools;33.0.0" \
          "platforms;android-33" \
          "platforms;android-30"

        # Install Python dependencies
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: ./bin/*.apk
