name: Build APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Используем актуальную версию actions/checkout

    - name: Set up Python
      uses: actions/setup-python@v5  # Используем актуальную версию actions/setup-python
      with:
        python-version: '3.9'  # Устанавливаем Python 3.9 (или другую нужную версию)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        pip install cython
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y zipalign

    - name: Build APK
      run: |
        cd /path/to/your/project  # Укажите путь к вашему проекту
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: /path/to/your/project/bin/*.apk  # Укажите путь к вашему APK файлу

