name: Build APK with Buildozer

on:
  push:
    branches:
      - master  # Запускать workflow на push в ветку master

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последний образ Ubuntu для сборки

    steps:
    # Шаг 1: Проверяем код из репозитория
    - name: Checkout repository
      uses: actions/checkout@v3

    # Шаг 2: Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Установите нужную версию Python

    # Шаг 3: Устанавливаем зависимости (cython и buildozer)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython buildozer

    # Шаг 4: Устанавливаем зависимости для Android
    - name: Install Android dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-11-jdk \
          unzip \
         
